/*
 * Basics of Computer Graphics Exercise
 *
 * DO NOT EDIT THIS FILE!
 */

#ifndef ASSIGNMENT_H
#define ASSIGNMENT_H

#define _USE_MATH_DEFINES
#include "main.h"
#include <iostream>
#include <math.h>
void drawScaledCircle(float scaleX,float scaleY,glm::vec3 color);
void drawScaledTranslatedCircle(float scaleX,float scaleY,float transX, float transY,glm::vec3 color);
void drawTranslatedScaledRotatedCircle(float scaleX,float scaleY,float transX, float transY,float rot,glm::vec3 color);
void drawScene( int scene, float runTime );
void initCustomResources();
void deleteCustomResources();
void printStudents();

#endif
